<?php
/**
 * @file
 * Contains tests to manually test registry_autoload module functionality.
 */

/**
 * Test function to test class loading.
 */
function registry_autoload_test_class_loading() {
  $x = new \Drupal\Core\Cache\RegistryAutoloadTestTest();
  $x = new \Drupal\registry_autoload_test\Cache\RegistryAutoloadTestTest();
  $x = new \RegistryAutoloadTestTest();
  $x = new \custom\some\name\space\RegistryAutoloadTestTest();
  unset($x);
}
